//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSchedule.DataLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolScheduleDBEntities : DbContext
    {
        public SchoolScheduleDBEntities()
            : base("name=SchoolScheduleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<SchoolRole> SchoolRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CourseStatu> CourseStatus { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<UserCourse> UserCourses { get; set; }
        public virtual DbSet<UserProfileView> UserProfileViews { get; set; }
        public virtual DbSet<UserCoursesView> UserCoursesViews { get; set; }
    
        public virtual ObjectResult<RemainingCoursesSP_Result> RemainingCoursesSP(Nullable<System.Guid> userId, Nullable<System.Guid> degreeId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var degreeIdParameter = degreeId.HasValue ?
                new ObjectParameter("degreeId", degreeId) :
                new ObjectParameter("degreeId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RemainingCoursesSP_Result>("RemainingCoursesSP", userIdParameter, degreeIdParameter);
        }
    }
}
