//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSchedule.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCourse
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CourseId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> Status { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> Semester { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
